"""Basic import smoke tests for project scaffold."""


def test_core_modules_import() -> None:
    """Ensure critical modules import without runtime errors."""
    import api.routes.analyze  # noqa: F401
    import api.routes.chat  # noqa: F401
    import api.routes.health  # noqa: F401
    import api.schemas.chat  # noqa: F401
    import api.schemas.rest  # noqa: F401
    import app.dependencies  # noqa: F401
    import biomechanics.movement_metrics  # noqa: F401
    import biomechanics.resting_metrics  # noqa: F401
    import detection.deficiencies  # noqa: F401
    import detection.deficiency_models  # noqa: F401
    import detection.findings  # noqa: F401
    import detection.models  # noqa: F401
    import detection.thresholds  # noqa: F401
    import orchestration.rest_pipeline  # noqa: F401
    import pose.converters  # noqa: F401
    import pose.mediapipe_pose  # noqa: F401
    import recommendations.exercises  # noqa: F401
    import src.analysis.router  # noqa: F401
    import src.analysis.frame_sampler  # noqa: F401
    import src.analysis.gemini_draft_normalizer  # noqa: F401
    import src.analysis.hf_knowledge_draft  # noqa: F401
    import src.analysis.knowledge_draft  # noqa: F401
    import src.analysis.knowledge_projection  # noqa: F401
    import src.analysis.ocr  # noqa: F401
    import src.analysis.scene_detect  # noqa: F401
    import src.analysis.whisper_asr  # noqa: F401
    import src.analysis.youtube_fetch  # noqa: F401
    import src.chunking.align_segments  # noqa: F401
    import src.chunking.segment_builder  # noqa: F401
    import src.core.models  # noqa: F401
    import src.core.chat_models  # noqa: F401
    import src.core.settings  # noqa: F401
    import src.indexing.embeddings  # noqa: F401
    import src.indexing.payloads  # noqa: F401
    import src.indexing.qdrant_store  # noqa: F401
    import src.indexing.sparse  # noqa: F401
    import src.ingestion.local_video  # noqa: F401
    import src.ingestion.webpage  # noqa: F401
    import src.ingestion.youtube  # noqa: F401
    import src.pipelines.process_source  # noqa: F401
    import src.pipelines.persist_knowledge  # noqa: F401
    import src.pipelines.process_video_local  # noqa: F401
    import src.pipelines.process_video_premium  # noqa: F401
    import src.pipelines.process_webpage  # noqa: F401
    import src.pipelines.reindex  # noqa: F401
    import src.rag.answering  # noqa: F401
    import src.rag.chat_flow  # noqa: F401
    import src.retrieval.hybrid  # noqa: F401
    import src.storage.supabase_store  # noqa: F401
    import src.storage.chat_store  # noqa: F401
    import src.squat.models  # noqa: F401
    import src.squat.biomechanics  # noqa: F401
    import src.squat.pipeline  # noqa: F401
    import src.squat.pose_video  # noqa: F401
    import src.squat.quality_gate  # noqa: F401
    import src.squat.registry  # noqa: F401
    import src.squat.segmentation  # noqa: F401
    import src.squat.video  # noqa: F401
    import scripts.process_rag_source  # noqa: F401
    import scripts.analyze_rag_segments  # noqa: F401
    import scripts.ask_rag  # noqa: F401
    import scripts.import_gemini_knowledge_drafts  # noqa: F401
    import scripts.query_rag_segments  # noqa: F401
    import scripts.sync_rag_knowledge_draft  # noqa: F401
    import video.youtube_shorts  # noqa: F401
    import video.gemini_knowledge  # noqa: F401
    import video.movement_knowledge_import  # noqa: F401
    import video.video_knowledge_registry  # noqa: F401
    import video.downloader  # noqa: F401
    import scripts.import_movement_knowledge_to_supabase  # noqa: F401
    import scripts.run_youtube_batch  # noqa: F401
    import scripts.sync_movement_knowledge_supabase  # noqa: F401
