/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "1.0";
export type Contract = "squat_case_report";
export type GeneratedAt = string;
export type CaseId = string;
export type Status =
  "registro_pendiente" | "registro_rechazado" | "analisis_parcial" | "no_apto_para_analisis" | "analisis_completo";
export type CaseRecordPath = string;
export type SchemaVersion1 = "1.0";
export type CaseId1 = string;
export type Stage = "extraccion_pose_2d";
export type Detector = "mediapipe_pose";
export type VideoPath = string;
export type MinVisibilityThreshold = number;
export type TotalFrames = number;
export type ProcessedFrames = number;
export type FramesWithPose = number;
export type ValidFrames = number;
export type ProcessedFramesPercentage = number;
export type ValidFramesPercentage = number;
export type MeanDetectedKeypoints = number;
export type LandmarksCsv = string;
export type FrameQualityCsv = string;
export type OverlayVideo = string;
export type ReviewVideo = string | null;
export type QualityPlot = string;
export type SummaryJson = string;
export type SchemaVersion2 = "1.0";
export type CaseId2 = string;
export type Stage1 = "segmentacion_temporal";
export type Signal = "hip_midpoint_y";
export type LandmarksCsv1 = string;
export type FrameQualityCsv1 = string;
export type Fps = number;
export type TotalFrames1 = number;
export type RepetitionsDetected = number;
export type RepetitionIndex = number;
export type StartFrame = number;
export type PeakDepthFrame = number;
export type EndFrame = number;
export type StartSeconds = number;
export type PeakDepthSeconds = number;
export type EndSeconds = number;
export type DescentDurationSeconds = number;
export type AscentDurationSeconds = number;
export type TotalDurationSeconds = number;
export type PeakHipMidpointY = number;
export type ValidFramesPercentage1 = number;
export type Repetitions = SquatRepetition[];
export type FramePhasesCsv = string;
export type RepetitionsCsv = string;
export type SegmentationPlot = string;
export type SummaryJson1 = string;
export type SchemaVersion3 = "1.0";
export type CaseId3 = string;
export type Stage2 = "control_calidad_analitica";
export type Status1 = "apto_para_analisis" | "revision_requerida" | "no_apto_para_analisis";
export type EligibleForAnalysis = boolean;
export type CheckId = string;
export type Description = string;
export type Severity = "exclusion" | "warning";
export type Passed = boolean;
export type Observed = string;
export type Requirement = string;
export type Checks = SquatQualityCheck[];
export type ExclusionReasons = string[];
export type Warnings = string[];
export type SummaryJson2 = string;
export type SchemaVersion4 = "1.0";
export type CaseId4 = string;
export type Stage3 = "variables_biomecanicas";
export type LandmarksCsv2 = string;
export type FramePhasesCsv1 = string;
export type NormalizationReference = "initial_shoulder_width";
export type InitialShoulderWidth = number;
export type ValidMetricFrames = number;
export type TotalFrames2 = number;
export type RepetitionIndex1 = number;
export type PeakDepthFrame1 = number;
export type ValidFramesPercentage2 = number;
export type TrunkInclinationAtPeakDeg = number | null;
export type TrunkMaxAbsDeg = number | null;
export type TrunkMaxAbsFrame = number | null;
export type PelvisShiftAtPeakPct = number | null;
export type PelvisMaxAbsShiftPct = number | null;
export type PelvisMaxAbsFrame = number | null;
export type LeftKneeMedialDeviationAtPeakPct = number | null;
export type RightKneeMedialDeviationAtPeakPct = number | null;
export type LeftKneeMaxMedialDeviationPct = number | null;
export type RightKneeMaxMedialDeviationPct = number | null;
export type BilateralAlignmentDifferenceAtPeakPct = number | null;
export type BilateralMaxAlignmentDifferencePct = number | null;
export type Repetitions1 = SquatRepetitionMetrics[];
export type Conventions = string[];
export type FrameMetricsCsv = string;
export type RepetitionMetricsCsv = string;
export type MetricsPlot = string;
export type SummaryJson3 = string;
export type SchemaVersion5 = "1.0";
export type CaseId5 = string;
export type Stage4 = "criterios_biomecanicos_interpretables";
export type RulesetVersion = string;
export type RulesetStatus = "provisional" | "frozen";
export type QualityGateStatus = "apto_para_analisis" | "revision_requerida" | "no_apto_para_analisis";
export type Finding = string;
export type Status2 = "presente" | "ausente" | "no_concluyente";
export type Direction = string | null;
export type Metric = string;
export type Unit = string;
export type AggregateValue = number | null;
export type RepetitionValues = (number | null)[];
export type RepetitionStates = ("presente" | "ausente" | "no_concluyente")[];
export type AbsentMax = number;
export type PresentMin = number;
export type Rationale = string;
export type Decisions = SquatRuleDecision[];
export type DetectedFindings = string[];
export type InconclusiveFindings = string[];
export type Notes = string[];
export type RuleEvidenceCsv = string;
export type FindingsJson = string;
export type OverlayVideo1 = string | null;
export type ReviewVideo1 = string | null;
export type LandmarksCsv3 = string | null;
export type FrameQualityCsv2 = string | null;
export type PoseQualityPlot = string | null;
export type FramePhasesCsv2 = string | null;
export type RepetitionsCsv1 = string | null;
export type SegmentationPlot1 = string | null;
export type BiomechanicalFrameMetricsCsv = string | null;
export type BiomechanicalRepetitionMetricsCsv = string | null;
export type BiomechanicalMetricsPlot = string | null;
export type RuleEvidenceCsv1 = string | null;
export type RepetitionIndex2 = number;
export type Event = "inicio_descenso" | "maxima_profundidad" | "final_ascenso";
export type FrameIndex = number;
export type TimestampSeconds = number;
export type RelativePath = string;
export type EventCaptures = SquatEventCapture[];
export type PipelineVersion = string;
export type Notes1 = string[];

/**
 * Instrument 2-oriented aggregate consumed by API clients.
 */
export interface SquatCaseReport {
  schema_version?: SchemaVersion;
  contract?: Contract;
  generated_at?: GeneratedAt;
  case_id: CaseId;
  status: Status;
  case_record_path: CaseRecordPath;
  pose?: SquatPoseSummary | null;
  segmentation?: SquatSegmentationSummary | null;
  quality?: SquatQualityGateSummary | null;
  biomechanics?: SquatBiomechanicsSummary | null;
  findings?: SquatFindingsSummary | null;
  artifacts?: SquatArtifactManifest;
  pipeline_version: PipelineVersion;
  notes?: Notes1;
}
/**
 * Aggregate quality indicators for pose extraction from one video.
 */
export interface SquatPoseSummary {
  schema_version?: SchemaVersion1;
  case_id: CaseId1;
  stage?: Stage;
  detector?: Detector;
  video_path: VideoPath;
  min_visibility_threshold: MinVisibilityThreshold;
  total_frames: TotalFrames;
  processed_frames: ProcessedFrames;
  frames_with_pose: FramesWithPose;
  valid_frames: ValidFrames;
  processed_frames_percentage: ProcessedFramesPercentage;
  valid_frames_percentage: ValidFramesPercentage;
  mean_detected_keypoints: MeanDetectedKeypoints;
  artifacts: SquatPoseArtifacts;
  [k: string]: unknown;
}
/**
 * Files generated by the temporal pose-extraction stage.
 */
export interface SquatPoseArtifacts {
  landmarks_csv: LandmarksCsv;
  frame_quality_csv: FrameQualityCsv;
  overlay_video: OverlayVideo;
  review_video?: ReviewVideo;
  quality_plot: QualityPlot;
  summary_json: SummaryJson;
  [k: string]: unknown;
}
/**
 * Aggregate result of temporal squat segmentation.
 */
export interface SquatSegmentationSummary {
  schema_version?: SchemaVersion2;
  case_id: CaseId2;
  stage?: Stage1;
  signal?: Signal;
  landmarks_csv: LandmarksCsv1;
  frame_quality_csv: FrameQualityCsv1;
  fps: Fps;
  total_frames: TotalFrames1;
  repetitions_detected: RepetitionsDetected;
  repetitions: Repetitions;
  artifacts: SquatSegmentationArtifacts;
  [k: string]: unknown;
}
/**
 * Temporal landmarks for one detected bilateral-squat repetition.
 */
export interface SquatRepetition {
  repetition_index: RepetitionIndex;
  start_frame: StartFrame;
  peak_depth_frame: PeakDepthFrame;
  end_frame: EndFrame;
  start_seconds: StartSeconds;
  peak_depth_seconds: PeakDepthSeconds;
  end_seconds: EndSeconds;
  descent_duration_seconds: DescentDurationSeconds;
  ascent_duration_seconds: AscentDurationSeconds;
  total_duration_seconds: TotalDurationSeconds;
  peak_hip_midpoint_y: PeakHipMidpointY;
  valid_frames_percentage: ValidFramesPercentage1;
  [k: string]: unknown;
}
/**
 * Files generated by the temporal segmentation stage.
 */
export interface SquatSegmentationArtifacts {
  frame_phases_csv: FramePhasesCsv;
  repetitions_csv: RepetitionsCsv;
  segmentation_plot: SegmentationPlot;
  summary_json: SummaryJson1;
  [k: string]: unknown;
}
/**
 * Decision on whether a processed video is usable for formal analysis.
 */
export interface SquatQualityGateSummary {
  schema_version?: SchemaVersion3;
  case_id: CaseId3;
  stage?: Stage2;
  status: Status1;
  eligible_for_analysis: EligibleForAnalysis;
  checks: Checks;
  exclusion_reasons: ExclusionReasons;
  warnings: Warnings;
  artifacts: SquatQualityGateArtifacts;
  [k: string]: unknown;
}
/**
 * One explicit technical acceptance criterion.
 */
export interface SquatQualityCheck {
  check_id: CheckId;
  description: Description;
  severity: Severity;
  passed: Passed;
  observed: Observed;
  requirement: Requirement;
  [k: string]: unknown;
}
/**
 * Files generated by the analytical quality gate.
 */
export interface SquatQualityGateArtifacts {
  summary_json: SummaryJson2;
  [k: string]: unknown;
}
/**
 * Aggregate result of interpretable biomechanical calculations.
 */
export interface SquatBiomechanicsSummary {
  schema_version?: SchemaVersion4;
  case_id: CaseId4;
  stage?: Stage3;
  landmarks_csv: LandmarksCsv2;
  frame_phases_csv: FramePhasesCsv1;
  normalization_reference?: NormalizationReference;
  initial_shoulder_width: InitialShoulderWidth;
  valid_metric_frames: ValidMetricFrames;
  total_frames: TotalFrames2;
  repetitions: Repetitions1;
  conventions: Conventions;
  artifacts: SquatBiomechanicsArtifacts;
  [k: string]: unknown;
}
/**
 * Biomechanical measurements summarized for one repetition.
 */
export interface SquatRepetitionMetrics {
  repetition_index: RepetitionIndex1;
  peak_depth_frame: PeakDepthFrame1;
  valid_frames_percentage: ValidFramesPercentage2;
  trunk_inclination_at_peak_deg?: TrunkInclinationAtPeakDeg;
  trunk_max_abs_deg?: TrunkMaxAbsDeg;
  trunk_max_abs_frame?: TrunkMaxAbsFrame;
  pelvis_shift_at_peak_pct?: PelvisShiftAtPeakPct;
  pelvis_max_abs_shift_pct?: PelvisMaxAbsShiftPct;
  pelvis_max_abs_frame?: PelvisMaxAbsFrame;
  left_knee_medial_deviation_at_peak_pct?: LeftKneeMedialDeviationAtPeakPct;
  right_knee_medial_deviation_at_peak_pct?: RightKneeMedialDeviationAtPeakPct;
  left_knee_max_medial_deviation_pct?: LeftKneeMaxMedialDeviationPct;
  right_knee_max_medial_deviation_pct?: RightKneeMaxMedialDeviationPct;
  bilateral_alignment_difference_at_peak_pct?: BilateralAlignmentDifferenceAtPeakPct;
  bilateral_max_alignment_difference_pct?: BilateralMaxAlignmentDifferencePct;
  [k: string]: unknown;
}
/**
 * Files generated by the biomechanical-variable calculation stage.
 */
export interface SquatBiomechanicsArtifacts {
  frame_metrics_csv: FrameMetricsCsv;
  repetition_metrics_csv: RepetitionMetricsCsv;
  metrics_plot: MetricsPlot;
  summary_json: SummaryJson3;
  [k: string]: unknown;
}
/**
 * Multilabel output from the provisional interpretable rule engine.
 */
export interface SquatFindingsSummary {
  schema_version?: SchemaVersion5;
  case_id: CaseId5;
  stage?: Stage4;
  ruleset_version: RulesetVersion;
  ruleset_status: RulesetStatus;
  quality_gate_status: QualityGateStatus;
  decisions: Decisions;
  detected_findings: DetectedFindings;
  inconclusive_findings: InconclusiveFindings;
  notes: Notes;
  artifacts: SquatFindingsArtifacts;
  [k: string]: unknown;
}
/**
 * Traceable classification produced by one biomechanical rule.
 */
export interface SquatRuleDecision {
  finding: Finding;
  status: Status2;
  direction?: Direction;
  metric: Metric;
  unit: Unit;
  aggregate_value?: AggregateValue;
  repetition_values: RepetitionValues;
  repetition_states: RepetitionStates;
  absent_max: AbsentMax;
  present_min: PresentMin;
  rationale: Rationale;
  [k: string]: unknown;
}
/**
 * Files generated by the interpretable-rule stage.
 */
export interface SquatFindingsArtifacts {
  rule_evidence_csv: RuleEvidenceCsv;
  findings_json: FindingsJson;
  [k: string]: unknown;
}
/**
 * Portable relative paths exposed to an API or interface.
 */
export interface SquatArtifactManifest {
  overlay_video?: OverlayVideo1;
  review_video?: ReviewVideo1;
  landmarks_csv?: LandmarksCsv3;
  frame_quality_csv?: FrameQualityCsv2;
  pose_quality_plot?: PoseQualityPlot;
  frame_phases_csv?: FramePhasesCsv2;
  repetitions_csv?: RepetitionsCsv1;
  segmentation_plot?: SegmentationPlot1;
  biomechanical_frame_metrics_csv?: BiomechanicalFrameMetricsCsv;
  biomechanical_repetition_metrics_csv?: BiomechanicalRepetitionMetricsCsv;
  biomechanical_metrics_plot?: BiomechanicalMetricsPlot;
  rule_evidence_csv?: RuleEvidenceCsv1;
  event_captures?: EventCaptures;
}
/**
 * One anonymized visual checkpoint for a detected repetition.
 */
export interface SquatEventCapture {
  repetition_index: RepetitionIndex2;
  event: Event;
  frame_index: FrameIndex;
  timestamp_seconds: TimestampSeconds;
  relative_path: RelativePath;
}
