/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type SchemaVersion = "1.0";
export type Contract = "squat_case_record";
export type CreatedAt = string;
export type SchemaVersion1 = "1.0";
export type AnalysisId = string;
export type CreatedAt1 = string;
export type Stage = "registro_tecnico";
export type Status = "pendiente_revision_protocolo" | "listo_para_pose" | "rechazado";
export type ReadyForPose = boolean;
export type CaseId = string;
export type VideoPath = string;
export type ParticipantCode = string | null;
export type Profile = "positivo_controlado" | "negativo" | "no_etiquetado";
export type IntendedFindings = string[];
export type ProtocolReviewStatus = "pendiente" | "aceptado" | "rechazado";
export type ExclusionReason = string | null;
export type View = "anterior";
export type Plane = "frontal";
export type LoadCondition = "sin_carga_externa";
export type Path = string;
export type Suffix = string;
export type WidthPx = number;
export type HeightPx = number;
export type Fps = number;
export type FrameCount = number;
export type DurationSeconds = number;
export type FirstFrameReadable = boolean;
export type CriticalLandmarks = string[];
export type TargetFindings = string[];
export type Notes = string[];
export type RecordDate = string | null;
export type VideoSource = string | null;
export type CaptureDevice = string | null;
export type Lighting = "adecuada" | "regular" | "deficiente" | "no_verificada";
export type Background = "adecuado" | "regular" | "deficiente" | "no_verificado";
export type BodyVisibility = "completa" | "parcial_utilizable" | "insuficiente" | "no_verificada";
export type Occlusions = "ninguna" | "leve" | "moderada" | "severa" | "no_verificada";
export type CompleteSquatObservable = boolean | null;
export type Surface = "plana" | "no_plana" | "no_verificable";
export type ExternalHeelSupport = "no" | "si" | "no_verificable";
export type ApparentHeelContact = "continuo" | "elevacion_breve" | "elevacion_evidente_o_sostenida" | "no_verificable";
export type SupportConditionCompliant = boolean | null;
export type PlantarSupportObservation = string | null;
export type ReviewedBy = string | null;
export type ReviewedAt = string | null;

/**
 * Instrument 1 contract persisted before computational analysis.
 */
export interface SquatCaseRecordContract {
  schema_version?: SchemaVersion;
  contract?: Contract;
  created_at?: CreatedAt;
  registration: SquatRegistrationResult;
  manual_protocol_review: SquatManualProtocolReview;
}
/**
 * Baseline output produced before pose extraction starts.
 */
export interface SquatRegistrationResult {
  schema_version?: SchemaVersion1;
  analysis_id: AnalysisId;
  created_at?: CreatedAt1;
  stage?: Stage;
  status: Status;
  ready_for_pose: ReadyForPose;
  case: SquatCaseRecord;
  video: VideoTechnicalMetadata;
  critical_landmarks?: CriticalLandmarks;
  target_findings?: TargetFindings;
  notes?: Notes;
  [k: string]: unknown;
}
/**
 * Traceable record for one frontal bilateral-squat video.
 */
export interface SquatCaseRecord {
  case_id: CaseId;
  video_path: VideoPath;
  participant_code?: ParticipantCode;
  profile?: Profile;
  intended_findings?: IntendedFindings;
  protocol_review_status?: ProtocolReviewStatus;
  exclusion_reason?: ExclusionReason;
  view?: View;
  plane?: Plane;
  load_condition?: LoadCondition;
  [k: string]: unknown;
}
/**
 * Technical properties obtained without biomechanical interpretation.
 */
export interface VideoTechnicalMetadata {
  path: Path;
  suffix: Suffix;
  width_px: WidthPx;
  height_px: HeightPx;
  fps: Fps;
  frame_count: FrameCount;
  duration_seconds: DurationSeconds;
  first_frame_readable: FirstFrameReadable;
  [k: string]: unknown;
}
/**
 * Manual Instrument 1 fields that cannot be inferred by the pose model.
 */
export interface SquatManualProtocolReview {
  record_date?: RecordDate;
  video_source?: VideoSource;
  capture_device?: CaptureDevice;
  lighting?: Lighting;
  background?: Background;
  body_visibility?: BodyVisibility;
  occlusions?: Occlusions;
  complete_squat_observable?: CompleteSquatObservable;
  surface?: Surface;
  external_heel_support?: ExternalHeelSupport;
  apparent_heel_contact?: ApparentHeelContact;
  support_condition_compliant?: SupportConditionCompliant;
  plantar_support_observation?: PlantarSupportObservation;
  landmark_availability?: LandmarkAvailability;
  reviewed_by?: ReviewedBy;
  reviewed_at?: ReviewedAt;
}
export interface LandmarkAvailability {
  [k: string]: "B" | "I" | "D" | "O" | "N" | "C";
}
